[project]
name = "papaya-iiif"
version = "1.2.0"
description = "IIIF Presentation API implementation"
authors = [
    { name='University of Maryland Libraries', email='lib-ssdr@umd.edu' },
    { name='Peter Eichman', email='peichman@umd.edu' },
    { name='David Steelman', email='dsteelma@umd.edu' },
    { name='Marc Andreu Grillo Aguilar', email='aguilarm@umd.edu' },
]
readme = "README.md"
requires-python = ">= 3.14"
dependencies = [
    "click",
    "configurenv",
    "codetiming",
    "flask",
    "jq",
    "pysolr",
    "python-dotenv",
    "pyyaml",
    "requests",
    "urlobject",
    "waitress",
]

[dependency-groups]
test = [
    "pytest",
    "pytest-cov",
    "ruff",
]
docs = [
    "pdoc",
]

[project.scripts]
papaya = "papaya.server:run"

[tool.pytest.ini_options]
addopts = "--doctest-modules"

[tool.ruff]
line-length = 120

[tool.ruff.format]
quote-style = "single"
